name: tastez
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # dependencies: recipepage
  flutter_html: ^1.0.0

  # dependencies: intro
  intro_slider: ^2.3.3
  permission_handler: '^3.2.0'

  # dependencies: search
  dropdown_search: ^0.4.5
  http: ^0.12.2
  dio: ^3.0.10
  holding_gesture: ^0.0.3

  # dependencies: pantry
  grouped_buttons: ^1.0.4

  # dependencis: db
  sqflite:
  path:
  shared_preferences: ^0.5.12+2
  path_provider: ^1.6.22

  # dependencies: auth
  password: ^1.0.0
  google_sign_in: ^4.5.5
  sign_in_with_apple: ^2.5.4
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3



dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/tutorialImages/tutorialFavorites.png
    - assets/tutorialImages/tutorialHome.png
    - assets/tutorialImages/tutorialList.png
    - assets/tutorialImages/tutorialPantry.png
    - assets/tutorialImages/tutorialRecipePage.png
    - assets/tutorialImages/tutorialSearch.png

    # Images for the tutorial
    - assets/tutorialImages/tutorialFavorites.png
    - assets/tutorialImages/tutorialHome.png
    - assets/tutorialImages/tutorialList.png
    - assets/tutorialImages/tutorialPantry.png
    - assets/tutorialImages/tutorialRecipePage.png
    - assets/tutorialImages/tutorialSearch.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
