import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:tastez/SelectIngredients.dart';
import 'home.dart';
import 'SelectIngredients.dart';
import 'package:grouped_buttons/grouped_buttons.dart';

// final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();

// Widget pantry() {
//   return Container(
//     //padding: EdgeInsets.symmetric(vertical: 20.0, horizontal: 10.0),
//     //margin: EdgeInsets.symmetric(vertical: 10.0, horizontal: 5.0),
//     margin: EdgeInsets.fromLTRB(10, 15, 10, 0),
//     child: Column(
//       crossAxisAlignment: CrossAxisAlignment.stretch,
//       children: [
//         topButton(),
//         SizedBox(height: 7.0),
//         bottomButton(),
//         SizedBox(height: 5.0),
//       ],
//     ),
//   );
// }

// Widget buttonTemplate(text, ){
//   return FlatButton(
//     color: Colors.blue,
//     textColor: Colors.white,
//     disabledColor: Colors.grey,
//     disabledTextColor: Colors.black,
//     padding: EdgeInsets.symmetric(vertical: 10, horizontal: 15),
//     splashColor: Colors.blueAccent,
//     onPressed: () {
//       /*...*/
//     },
//     child: Text(
//       '$text',
//       style: TextStyle(fontSize: 20.0),
//     ),
//   );
// }

// Widget topButton(){
//   return FlatButton(
//     color: Colors.blue,
//     textColor: Colors.white,
//     disabledColor: Colors.grey,
//     disabledTextColor: Colors.black,
//     padding: EdgeInsets.symmetric(vertical: 10, horizontal: 15),
//     splashColor: Colors.blueAccent,
//     onPressed: () {
//       //SelectIngredients();
//       print("Select ingredients is pressed");
//       // Navigator.push(context, MaterialPageRoute(builder: (context) => SelectIngredients()));
//     },
//     child: Text(
//       "Select Ingredients",
//       style: TextStyle(fontSize: 20.0),
//     ),
//   );
// }



// Widget bottomButton(){
//   return FlatButton(
//     color: Colors.blue,
//     textColor: Colors.white,
//     disabledColor: Colors.grey,
//     disabledTextColor: Colors.black,
//     padding: EdgeInsets.symmetric(vertical: 10, horizontal: 15),
//     splashColor: Colors.blueAccent,
//     onPressed: () {
//       print("Suggested Recipes is pressed");
//     },
//     child: Text(
//       "Suggested Recipes",
//       style: TextStyle(fontSize: 20.0),
//     ),
//   );
// }

Widget pantry(){
    //dairy
    return Container(
      child:
          ListView(children: [
            Container(
              padding: const EdgeInsets.only(left: 14.0, top: 14.0),
              child: Text("Dairy",
                style: TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 20.0
                ),
              ),
            ),
            CheckboxGroup( //Dairy
              labels: <String>[
                "Milk",
                "Butter",
                "Buttermilk",
                "Cheese",
                "Cream",
                "Crème Fraiche",
                "Egg",
                "Ghee",
                "Half and Half",
                "Sour Cream",
                "Yogurt",
              ],
              onChange: (bool isChecked, String label, int index) => print("isChecked: $isChecked   label: $label  index: $index"),
              onSelected: (List<String> checked) => print("checked: ${checked.toString()}"),
            ),
            Container(
              padding: const EdgeInsets.only(left: 14.0, top: 14.0),
              child: Text("Flour",
                style: TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 20.0
                ),
              ),
            ),
            CheckboxGroup( //Flour
              labels: <String>[
                "Cake Flour",
                "Chickpea Flour",
                "Cornmeal",
                "Cornstarch",
                "Graham Flour",
                "Maida",
                "Pastry Flour",
                "Rice Flour",
                "Self-rising Flour",
                "Tapoica Starch",
                "Whole Wheat Flour",
              ],
              onChange: (bool isChecked, String label, int index) => print("isChecked: $isChecked   label: $label  index: $index"),
              onSelected: (List<String> checked) => print("checked: ${checked.toString()}"),
            ),
            Container(
              padding: const EdgeInsets.only(left: 14.0, top: 14.0),
              child: Text("Fruit",
                style: TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 20.0
                ),
              ),
            ),
            CheckboxGroup( //Fruit
              labels: <String>[
                "Apple",
                "Avocado",
                "Banana",
                "Blackberry",
                "Blueberry",
                "Breadfruit",
                "Cherry",
                "Chokeberry",
                "Coconut",
                "Cranberry",
                "Date",
                "Durian",
                "Feijoa",
                "Fig",
                "Grape",
                "Grapefruit",
                "Guava",
                "Haw",
                "Horned Melon",
                "Jackfruit",
                "Juneberry",
                "Kiwifruit",
                "Kumquat",
                "Lemon",
                "Lime","Longan",
                "Lychee",
                "Mango",
                "Medlar",
                "Melon",
                "Nectarine",
                "Olive",
                "Orange",
                "Papaya",
                "Passion Fruit",
                "Pawpaw",
                "Peach",
                "Pear",
                "Pepino",
                "Persimmon",
                "Pineapple",
                "Plantain",
                "Plum",
                "Pomegranate",
                "Prickly Pear",
                "Pummelo",
                "Quince",
                "Raisin",
                "Rambutan",
                "Rasberry",
                "Sapote",
                "Star Fruit",
                "Strawberry",
                "Tamarillo",
                "Tamarind",
                "Tangerine",
                "Ugli Fruit",
                "Watermelon",
              ],
              onChange: (bool isChecked, String label, int index) => print("isChecked: $isChecked   label: $label  index: $index"),
              onSelected: (List<String> checked) => print("checked: ${checked.toString()}"),
            ),
            Container(
              padding: const EdgeInsets.only(left: 14.0, top: 14.0),
              child: Text("Meat and Poultry",
                style: TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 20.0
                ),
              ),
            ),
            CheckboxGroup( //Meat and Poultry
              labels: <String>[
                "Bacon",
                "Beef",
                "Bison",
                "Chicken",
                "Chorizo",
                "Cornish Hen",
                "Duck",
                "Foie Gras",
                "Giblets",
                "Goat",
                "Ham",
                "Hot Dog",
                "Kidney",
                "Lamb",
                "Liver",
                "Mutton",
                "Organ Meat",
                "Panchetta",
                "Pastrami",
                "Pepperoni",
                "Pork",
                "Prosciutto",
                "Quail",
                "Rabbit",
                "Salami",
                "Sausage",
                "Tongue",
                "Tripe",
                "Turkey",
                "Veal",
                "Venison",
              ],
              disabled: [
                "Bison",
              ],
              onChange: (bool isChecked, String label, int index) => print("isChecked: $isChecked   label: $label  index: $index"),
              onSelected: (List<String> checked) => print("checked: ${checked.toString()}"),
            ),
            Container(
              padding: const EdgeInsets.only(left: 14.0, top: 14.0),
              child: Text("Herbs and Spices",
                style: TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 20.0
                ),
              ),
            ),
            CheckboxGroup(//Herbs and Spices
              labels: <String>[
                "Allspice",
                "Annatto",
                "Asafoetida",
                "Basil",
                "Bay Leaf",
                "Black Salt",
                "Caraway",
                "Cardamon",
                "Celery Seed",
                "Chervil",
                "Chicory",
                "Chili Powder",
                "Cilantro",
                "Cinnamon",
                "Coriander",
                "Culantro",
                "Cumin",
                "Dill",
                "Fennel",
                "Fenugreek",
                "Galangal",
                "Garlic",
                "Garlic Powder",
                "Ginger",
                "Green Onion",
                "Juniper Berry",
                "Lemongrass",
                "Mint",
                "Mixed Spice",
                "MSG",
                "Mustard",
                "Nutmeg",
                "Oregano",
                "Paprika",
                "Parsley",
                "Pepper",
                "Rosemary",
                "Saffron",
                "Sage",
                "Serrano Chili",
                "Star Anise",
                "Szechuan Pepper",
                "Tamarind",
                "Tarragon",
                "Thyme",
                "Tumeric",
                "Vanilla",
                "Wasabi",
                "Zhug",
              ],
              onChange: (bool isChecked, String label, int index) => print("isChecked: $isChecked   label: $label  index: $index"),
              onSelected: (List<String> checked) => print("checked: ${checked.toString()}"),
            ),
            Container(
              padding: const EdgeInsets.only(left: 14.0, top: 14.0),
              child: Text("Nut and Seeds",
                style: TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 20.0
                ),
              ),
            ),
            CheckboxGroup( //Nut and Seeds
              labels: <String>[
                "Candlenut",
                "Cashew",
                "Chestnut",
                "Macadamia",
                "Peanut",
                "Pecan",
                "Pine Nut",
                "Pistachio",
                "Poppy Seed",
                "Quinoa",
                "Sesame Seed",
                "Sunflower Seeds",
                "Tahini",
                "Walnut",
              ],
              onChange: (bool isChecked, String label, int index) => print("isChecked: $isChecked   label: $label  index: $index"),
              onSelected: (List<String> checked) => print("checked: ${checked.toString()}"),
            ),
            Container(
              padding: const EdgeInsets.only(left: 14.0, top: 14.0),
              child: Text("Seafood",
                style: TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 20.0
                ),
              ),
            ),
            CheckboxGroup( //Seafood
              labels: <String>[
                "Catfish",
                "Caviar",
                "Cod",
                "Crab"
                "Crabstick",
                "Eel",
                "Frog",
                "Hagfish",
                "Octopus",
                "Salmon"
                "Scallop",
                "Sea Cucumber"
                "Shellfish",
                "Shrimp",
                "Snail",
                "Snoek",
                "Squid",
                "Trout",
                "Tuna",
              ],
              onChange: (bool isChecked, String label, int index) => print("isChecked: $isChecked   label: $label  index: $index"),
              onSelected: (List<String> checked) => print("checked: ${checked.toString()}"),
            ),
            Container(
              padding: const EdgeInsets.only(left: 14.0, top: 14.0),
              child: Text("Vegetables",
                style: TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 20.0
                ),
              ),
            ),
            CheckboxGroup(//Vegetables
              labels: <String>[
                "Acorn Squash",
                "Alfalfa",
                "Artichoke",
                "Argula",
                "Asparagus",
                "Azuki Bean",
                "Bean Sprout",
                "Beet",
                "Bell Pepper",
                "Brassicas",
                "Broad Bean",
                "Butternut Squash",
                "Carrot",
                "Cassava",
                "Celery",
                "Chayote",
                "Chickpea",
                "Chicory",
                "Chiles",
                "Chufa",
                "Colcannon",
                "Collard Greens",
                "Cucumber",
                "Daikon",
                "Dal",
                "Drumstick",
                "Edible Cactus",
                "Eggplant",
                "Fava Bean",
                "Fennel",
                "Fenugreek",
                "Fiddlehead",
                "Florence Fennel",
                "Frisee",
                "Garlic",
                "Gem Squash",
                "Green Bean",
                "Green Onion",
                "Green Pepper",
                "Habanero",
                "Heart of Palm",
                "Hop Shoot",
                "Horse Radish",
                "Jicama",
                "Kale",
                "Kangkung",
                "Kidney Bean",
                "Kohlarbi",
                "Leek",
                "Legumes",
                "Lemongrass",
                "Lentil",
                "Lettuce",
                "Lima Bean",
                "Mung Bean",
                "Mushroom",
                "Nettle",
                "Nori",
                "Okra",
                "Onion",
                "Pea",
                "Pepperoncini",
                "Pigeon Pea",
                "Pimento",
                "Potato",
                "Pumpkin",
                "Radish",
                "Rhubarb",
                "Romaine Lettuce",
                "Runner Bean",
                "Rutabaga",
                "Salsify",
                "Samphire",
                "Shallot",
                "Snow Pea",
                "Spinach",
                "Spirulina",
                "Squash",
                "Stinging Nettle",
                "Sunchoke",
                "Sweet Potato",
                "Swiss Chard",
                "Taro Root",
                "The Trinity",
                "Tigernut",
                "Tomatillo",
                "Tomato",
                "Truffle",
                "Turnip",
                "Urad Bean",
                "Water Chestnut",
                "Watercress",
                "White Mushroom",
                "Yam",
                "Yardlong Bean",
                "Yu CHoy",
                "Zucchini",
              ],
              onChange: (bool isChecked, String label, int index) => print("isChecked: $isChecked   label: $label  index: $index"),
              onSelected: (List<String> checked) => print("checked: ${checked.toString()}"),
            ),
          ],)


    );
}